[project]
name = "poc-trustpilot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "petre", email = "boteapetre2@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
poc-trustpilot = "poc_trustpilot:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
