[project]
name = "poc-trustpilot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "petre", email = "boteapetre2@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "emoji>=2.16.0",
    "ipykernel>=7.4.0",
    "jupyter>=1.1.1",
    "lingua-language-detector>=2.1.1",
    "matplotlib>=3.11.2",
    "nbconvert>=7.17.1",
    "nbformat>=5.11.1",
    "nltk>=3.10.3",
    "pandas>=3.0.6",
    "seaborn>=0.13.2",
]

[project.scripts]
poc-trustpilot = "poc_trustpilot:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
