[project]
name = "poc-trustpilot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "petre", email = "boteapetre2@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "anthropic>=1.11.0",
    "emoji>=2.16.0",
    "ipykernel>=7.4.0",
    "jupyter>=1.1.1",
    "leidenalg>=0.12.0",
    "lingua-language-detector>=2.1.1",
    "matplotlib>=3.11.2",
    "nbconvert>=7.17.1",
    "nbformat>=5.11.1",
    "networkx>=3.6.1",
    "nltk>=3.10.3",
    "pandas>=3.0.6",
    "pyarrow>=25.0.1",
    "python-dotenv>=1.2.4",
    "python-igraph>=1.0.0",
    "pyvis>=0.3.2",
    "rapidfuzz>=3.14.6",
    "seaborn>=0.13.2",
    "streamlit>=1.65.0",
]

[project.scripts]
poc-trustpilot = "poc_trustpilot:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
